name: Publish React library to npm

on:
  push:
    branches:
      - publish-react

jobs:
  publish-library:
    uses: comlyboy/ci-cd-workflow-templates/.github/workflows/publish-npm-package.yml@main
    with:
      working_directory: 'react'
    secrets: inherit
