name: Publish Node library to npm

on:
  push:
    branches:
      - publish-node

# jobs:
#   publish-library:
#     uses: comlyboy/ci-cd-workflow-templates/.github/workflows/publish-npm-package.yml@main
#     with:
#       working_directory: 'node'
#     secrets: inherit


jobs:
  publish-library:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'node'

    steps:
      - name: Checkout code (make repo branch code available in this pipeline)
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set npm Authentication
        run: |
          echo "*** Authenticating with npm ***"
          echo "//registry.npmjs.org/:_authToken=${{ secrets._NPM_TOKEN }}" > ~/.npmrc
          echo "*** Authenticate with npm successful!!! ***"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check if version already published
        run: |
          VERSION=$(node -p "require('./package.json').version")
          NAME=$(node -p "require('./package.json').name")
          if npm view "$NAME@$VERSION" > /dev/null 2>&1; then
            echo "Version $VERSION already exists on npm. Skipping publish."
            exit 0
          fi

      - name: Publish to npm
        run: npm publish --access=public
