name: Publish library to npm

on:
  push:
    branches:
      - publish

jobs:
  publish-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (make repo branch code available in this pipeline)
        uses: actions/checkout@v4

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Authenticate with npm
        run: |
          echo "*** Authenticating with npm ***"
          echo "//registry.npmjs.org/:_authToken=${{ secrets._NPM_TOKEN }}" >> .npmrc
          echo "*** Authenticate with npm successfull!!! ***"

      - name: Install dependencies
        run: npm ci

      - name: build
        run: npm run build

      - name: Publish
        run: npm publish --access=public
